language: generic
sudo: false
cache:
  directories:
  - "$HOME/.stack-work"
env:
  global:
    secure: ENYFe1pGJQx/kA4X5i4niakLIRTV+LepuFcHpZzI+6mF8sCfwqmx5HEOOirUlq4UyPueyVHjdQ7IUJ2VQFHMDniSp+dkt1iu5gKyPA7jMZv8x8RGRBCRvl4CuOGIPTJS2OQBgAwY+mP9eFUuYIZ+SxOFyW8jzxv/zcOQUto7FFjA/VuPCFvAMO/swB9b5I/mQi8nX2kNNmO0wQaRH373ckGRX1fa7rrMNV5F1fG4atCl4zD2l1HYVueR99Hke0aro8vhma8CY1PVYzQYnOHco1nUGObcXdNKvJSs+wZ5FWjo5gxb53DDCIBfg8Stq7m4NIjIKKMETCbs6XBqIKsLlZM0443GoOFaeRjtTNQaQnlJkZo8s75wfDHHOMGVL+72suDD6bYIzsvBtQeltt5z+X+nY0Pjkt75wzjnc0uyQmXzQS8+gmb9op2tG+Y4riA8mIdLuY8KLkfpNqQLZ3HwuzU89x3SmT2m9TgH5WZsrVA5mOr+8vyqQnOb/p7sZsLspsuxsK7pHm5euEYwyAt5H6DbKrJKe16NElLbch5pxbohpJREjt2QzOjo1dwDlzaH3ltgp2mJE8xmdHowXM4gRdd1EYEVwbvjwdAxz+ijvsT6mGLadIlgd8smS51yf8WlAn4nclKQcTHGxnJdqy/B/iHUvOP0pTEDlwaQ7jNU2a0=
addons:
  apt:
    packages:
    - haskell-stack
install:
- "./site.hs build"
script:
- echo 0
deploy:
  skip_cleanup: true
  provider: script
  script: "./deploy.sh"
  on:
    branch: master
